# This is AI generated code
"""Re-export shim for the per-flavour helper modules.

Existing call sites use ``from .helpers import X``. The
real homes are ``helpers_logic`` (pure),
``helpers_runtime`` (runtime-HA, TYPE_CHECKING-only HA
imports), and ``helpers_lifecycle`` (lifecycle, function-
body HA imports OK). Callers don't need to track which
file owns each symbol.

Add a new helper to whichever file matches its
HA-dependency profile and re-export from this shim --
``TestHelpersShimReExportsEveryPublicSymbol`` (in
``tests/test_helpers_lifecycle.py``) catches drift if a
new public symbol lands in a flavour file but the shim
re-export is forgotten.
"""

from __future__ import annotations

from .helpers_lifecycle import (
    all_integration_ids,
    cv_ha_domain_list,
    file_editor_addon_ingress_url,
    integration_entity_ids,
    make_lifecycle_mutators,
    process_repairs_with_sweep,
    register_blueprint_handler,
    schedule_periodic_with_jitter,
)
from .helpers_logic import (
    CONTROLLABLE_DOMAINS,
    BlueprintHandlerSpec,
    CappableResult,
    DeviceRef,
    FixService,
    Issue,
    IssueNotification,
    JoinedRegexLine,
    JoinedRegexResult,
    LifecycleMutators,
    PersistentNotification,
    TypedServiceResponse,
    UnmatchedDirective,
    automation_dashboard_link,
    automation_edit_link,
    automation_edit_url,
    config_entry_link,
    config_entry_url,
    dashboard_link,
    dashboard_url,
    device_attribution_lines,
    device_entity_link,
    device_entity_url,
    device_link,
    device_url,
    deviceless_entity_link,
    domain_entities_link,
    domain_entities_url,
    entities_dashboard_url,
    file_editor_link,
    format_notification,
    format_timestamp,
    instance_state_entity_id,
    integration_attribution_link,
    integration_link,
    integration_url,
    make_config_error_notification,
    make_emit_config_error,
    make_unmatched_directives_notification,
    matches_pattern,
    md_escape,
    notification_prefix,
    repair_notification_id,
    resolve_target_integrations,
    script_dashboard_link,
    script_edit_link,
    script_edit_url,
    slugify,
    spec_bucket,
    validate_and_join_regex_patterns,
    validate_controlled_entity_domains,
    validate_directives_item,
    validate_directives_regex,
)
from .helpers_runtime import (
    attribution_lines,
    automation_friendly_name,
    dismiss_fix_service_crash_notification,
    emit_config_error,
    emit_fix_service_crash_notification,
    entity_friendly_names,
    entry_for_domain,
    filter_on_entities,
    make_periodic_trigger_callback,
    prepare_notifications,
    process_persistent_notifications,
    process_persistent_notifications_with_sweep,
    register_fix_service,
    unregister_blueprint_handler,
    update_instance_state,
    validate_payload_or_emit_config_error,
)

__all__ = [
    "BlueprintHandlerSpec",
    "CONTROLLABLE_DOMAINS",
    "CappableResult",
    "DeviceRef",
    "FixService",
    "Issue",
    "IssueNotification",
    "JoinedRegexLine",
    "JoinedRegexResult",
    "LifecycleMutators",
    "PersistentNotification",
    "TypedServiceResponse",
    "UnmatchedDirective",
    "all_integration_ids",
    "attribution_lines",
    "automation_dashboard_link",
    "automation_edit_link",
    "automation_edit_url",
    "automation_friendly_name",
    "config_entry_link",
    "config_entry_url",
    "cv_ha_domain_list",
    "dashboard_link",
    "dashboard_url",
    "device_attribution_lines",
    "device_entity_link",
    "device_entity_url",
    "device_link",
    "device_url",
    "deviceless_entity_link",
    "dismiss_fix_service_crash_notification",
    "domain_entities_link",
    "domain_entities_url",
    "emit_config_error",
    "emit_fix_service_crash_notification",
    "entities_dashboard_url",
    "entity_friendly_names",
    "entry_for_domain",
    "file_editor_addon_ingress_url",
    "file_editor_link",
    "filter_on_entities",
    "format_notification",
    "format_timestamp",
    "instance_state_entity_id",
    "integration_attribution_link",
    "integration_entity_ids",
    "integration_link",
    "integration_url",
    "make_config_error_notification",
    "make_emit_config_error",
    "make_lifecycle_mutators",
    "make_periodic_trigger_callback",
    "make_unmatched_directives_notification",
    "matches_pattern",
    "md_escape",
    "notification_prefix",
    "prepare_notifications",
    "process_persistent_notifications",
    "process_persistent_notifications_with_sweep",
    "process_repairs_with_sweep",
    "register_blueprint_handler",
    "register_fix_service",
    "repair_notification_id",
    "resolve_target_integrations",
    "schedule_periodic_with_jitter",
    "script_dashboard_link",
    "script_edit_link",
    "script_edit_url",
    "slugify",
    "spec_bucket",
    "unregister_blueprint_handler",
    "update_instance_state",
    "validate_and_join_regex_patterns",
    "validate_controlled_entity_domains",
    "validate_directives_item",
    "validate_directives_regex",
    "validate_payload_or_emit_config_error",
]
